config/routes.rb
BTVProject::Application.routes.draw do

  get "schedule/index"

  match "/board" => "board#index"
	match "/schedule" => "schedule#index"

  resources :videos
  get "sessions/new"

  get "sessions/create"

  get "sessions/failure"

  resources :authentications

  resources :posts

  match "about" => "home#about"
  match "contact" => "home#contact"
  match "shows" => "home#shows"
  match "schedule" => "home#schedule"
  match "join" => "home#join"
  match "Juncture" => "home#Juncture"
  match "BTV_News" => "home#BTV_News"
  match "Binghamton_Bro_Code" => "home#Binghamton_Bro_Code"
  match "BTV_Mornings" => "home#BTV_Mornings"
  match "Cup_of_Joe" => "home#Cup_of_Joe"
  match "Common_Occurances" => "home#Common_Occurances"
  match "Gametime!" => "home#Gametime!"
  match "What_4" => "home#What_4"
  match "Comics_Anonymous" => "home#Comics_Anonymous"

  get   '/login', :to => 'sessions#new', :as => :login
  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/auth/failure', :to => 'sessions#failure'
  resources :identities

  namespace :admin do
    root :to => "dashboard#index"
    resources :users, :except => ['new', 'create', 'edit'] do
      resource :board_info, :except => ['new', 'create', 'edit']
    end
    resources :videos, :except => ['new', 'create', 'edit'] do
      member do
        put "approve"
      end
    end
    match "/pending" => "videos#pending", :as => "pending_videos"
  end

  root :to => "home#index"

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ActiveRecord::Base
  has_many :user_roles, :dependent => :destroy
  has_many :Videos
  has_many :board_infos, :dependent => :destroy
  validates :name, :email, :presence => true
  has_many :authentications

  def description
    if self.user_roles.empty?
      "just a user"
    elsif self.board_infos.empty?
      "an admin with no board info"
    else
      "the #{self.board_infos[0].full_title}"
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  include AdminModule

  def index
    @users = User.find(:all)
  end

  def show
    @user = User.find(params[:id])
    @description = "#{@user.name} is currently #{@user.description}."
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:notice] = "Successfully edited user"
    else
      flash[:warning] = "Failed to edit user"
    end
    redirect_to admin_user_path(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.delete!
    redirect_to admin_users_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/index.html.haml
.container
  .span10.offset1
    %h1.text-center
      User Information
    %table.table.table-hover
      %thead
        %tr
          %th Name
          %th Email
          %th Position
      %tbody
        - @users.each do |user|
          %tr
            %td= link_to "#{user.name}", admin_user_path(user)
            %td= mail_to "#{user.email}"

    <br>
    = link_to "Back to Admin", admin_root_path

app/views/admin/users/show.html.haml
.container
  .span10.offset1
    %h1.text-center
      = "#{@user.name}'s Information"

    = form_for @user, :url => admin_user_path(params[:id]), :method => :put do |f|
      = f.label "name", "Name:"
      = f.text_field "name"
      = f.label "email", "Email:"
      = f.email_field "email"
      -#= label_tag "role", "Role:"
      -#= select_tag "role", "<option selected>User</option><option>President</option><option>Whatever</option>".html_safe
      %br
      = f.submit "Submit Changes", :confirm => "Change this user's information?"
    %br

    = @description
    %br
    = link_to "Change Status", admin_user_board_info_path(@user)
    %br
    %br

    = link_to "Back to users list", admin_users_path